### PR TITLE
pulled in constants from drivetrain

### PR DESCRIPTION
**Pull request by Irishumanoid**

### CODE REVIEW

**Comment by awfulbananas** [comment]
CI still fails in the build.gradle, this might be an issue with the CI testing, but we should still resolve it before merging

**Comment by Irishumanoid** [comment]
CI fails because it can't find the latest PhotonLib dependency, although it's in the vendordep folder adn builds locally.

**Review by awfulbananas — APPROVED** [review]
looks fine besides CI, I'll approve it, but we should still probably resolve the build error before merging

**Comment by Irishumanoid** [comment]
Try building locally and let me know if the build succeeds

**Comment by awfulbananas** [comment]
it works locally, so I'll merge, but we should add the missing dependencies to CI at some point soon

**Pull request merged**
